export const DEFAULT_INITIAL_BALANCE = 100_000_000.0; // Rp 100.000.000
export const BUY_BROKER_FEE_RATE = 0.0015; // 0.15%
export const SELL_BROKER_FEE_RATE = 0.0025; // 0.25%
export const SHARES_PER_LOT = 100;

export interface StockInfo {
  ticker: string;
  name: string;
  sector: string;
  basePrice: number;
  peRatio: number;
  marketCap: string;
  yahooSymbol: string;
  description: string;
}

export const STOCKS: StockInfo[] = [
  // ==========================================
  // 1. FINANCIALS (PERBANKAN & JASA KEUANGAN)
  // ==========================================
  {
    ticker: 'BBCA',
    name: 'Bank Central Asia Tbk',
    sector: 'Financials',
    basePrice: 10250,
    peRatio: 22.4,
    marketCap: '1.260 T',
    yahooSymbol: 'BBCA.JK',
    description: 'Bank swasta terbesar di Indonesia dengan kapitalisasi pasar terbesar di BEI.',
  },
  {
    ticker: 'BBRI',
    name: 'Bank Rakyat Indonesia (Persero) Tbk',
    sector: 'Financials',
    basePrice: 4890,
    peRatio: 12.8,
    marketCap: '741 T',
    yahooSymbol: 'BBRI.JK',
    description: 'Bank BUMN dengan fokus utama pembiayaan segmen UMKM dan mikro di Indonesia.',
  },
  {
    ticker: 'BMRI',
    name: 'Bank Mandiri (Persero) Tbk',
    sector: 'Financials',
    basePrice: 6550,
    peRatio: 10.9,
    marketCap: '611 T',
    yahooSymbol: 'BMRI.JK',
    description: 'Salah satu bank BUMN terbesar di Indonesia dengan aset korporasi terkuat.',
  },
  {
    ticker: 'BBNI',
    name: 'Bank Negara Indonesia (Persero) Tbk',
    sector: 'Financials',
    basePrice: 5300,
    peRatio: 9.4,
    marketCap: '197 T',
    yahooSymbol: 'BBNI.JK',
    description: 'Bank BUMN pelopor layanan perbankan internasional dan consumer banking.',
  },
  {
    ticker: 'BRIS',
    name: 'Bank Syariah Indonesia Tbk',
    sector: 'Financials',
    basePrice: 2850,
    peRatio: 18.2,
    marketCap: '131 T',
    yahooSymbol: 'BRIS.JK',
    description: 'Bank syariah terbesar di Indonesia hasil merger bank syariah BUMN.',
  },
  {
    ticker: 'BBTN',
    name: 'Bank Tabungan Negara (Persero) Tbk',
    sector: 'Financials',
    basePrice: 1320,
    peRatio: 5.8,
    marketCap: '18.6 T',
    yahooSymbol: 'BBTN.JK',
    description: 'Bank BUMN spesialis pembiayaan perumahan KPR subsidi dan komersial.',
  },
  {
    ticker: 'BDMN',
    name: 'Bank Danamon Indonesia Tbk',
    sector: 'Financials',
    basePrice: 2680,
    peRatio: 8.2,
    marketCap: '26.2 T',
    yahooSymbol: 'BDMN.JK',
    description: 'Bank swasta anggota MUFG Bank Group dengan jaringan multifinance Adira.',
  },
  {
    ticker: 'BNGA',
    name: 'Bank CIMB Niaga Tbk',
    sector: 'Financials',
    basePrice: 1840,
    peRatio: 7.1,
    marketCap: '46.2 T',
    yahooSymbol: 'BNGA.JK',
    description: 'Bank swasta terbesar kedua di Indonesia dari sisi aset, anak usaha CIMB Group.',
  },
  {
    ticker: 'BNLI',
    name: 'Bank Permata Tbk',
    sector: 'Financials',
    basePrice: 1010,
    peRatio: 11.5,
    marketCap: '36.4 T',
    yahooSymbol: 'BNLI.JK',
    description: 'Bank swasta nasional bagian dari Bangkok Bank Group Thailand.',
  },
  {
    ticker: 'PNBN',
    name: 'Bank Pan Indonesia Tbk',
    sector: 'Financials',
    basePrice: 1420,
    peRatio: 10.2,
    marketCap: '34.2 T',
    yahooSymbol: 'PNBN.JK',
    description: 'Bank komersial terkemuka dengan fokus pembiayaan komersial dan ritel.',
  },
  {
    ticker: 'MEGA',
    name: 'Bank Mega Tbk',
    sector: 'Financials',
    basePrice: 4980,
    peRatio: 17.6,
    marketCap: '58.4 T',
    yahooSymbol: 'MEGA.JK',
    description: 'Bank swasta bagian dari CT Corp dengan ekosistem ritel dan media terintegrasi.',
  },
  {
    ticker: 'ARTO',
    name: 'Bank Jago Tbk',
    sector: 'Financials',
    basePrice: 2420,
    peRatio: 85.0,
    marketCap: '33.5 T',
    yahooSymbol: 'ARTO.JK',
    description: 'Pelopor bank digital berbasis aplikasi terintegrasi dengan ekosistem GoTo.',
  },
  {
    ticker: 'AGRO',
    name: 'Bank Raya Indonesia Tbk',
    sector: 'Financials',
    basePrice: 280,
    peRatio: 45.0,
    marketCap: '6.4 T',
    yahooSymbol: 'AGRO.JK',
    description: 'Bank digital anak perusahaan Bank BRI dengan fokus gig economy.',
  },
  {
    ticker: 'BBHI',
    name: 'Allo Bank Indonesia Tbk',
    sector: 'Financials',
    basePrice: 910,
    peRatio: 21.0,
    marketCap: '19.8 T',
    yahooSymbol: 'BBHI.JK',
    description: 'Bank digital CT Corp yang terhubung dengan ekosistem Bukalapak dan Salim Group.',
  },
  {
    ticker: 'BJBR',
    name: 'Bank Pembangunan Daerah Jawa Barat dan Banten Tbk',
    sector: 'Financials',
    basePrice: 990,
    peRatio: 6.2,
    marketCap: '10.3 T',
    yahooSymbol: 'BJBR.JK',
    description: 'Bank BPD terbesar di Indonesia dengan dividen yield konsisten tinggi.',
  },
  {
    ticker: 'BJTM',
    name: 'Bank Pembangunan Daerah Jawa Timur Tbk',
    sector: 'Financials',
    basePrice: 620,
    peRatio: 5.9,
    marketCap: '9.3 T',
    yahooSymbol: 'BJTM.JK',
    description: 'Bank BPD Jawa Timur dengan rasio profitabilitas kuat dan dividen rutin.',
  },
  {
    ticker: 'BFIN',
    name: 'BFI Finance Indonesia Tbk',
    sector: 'Financials',
    basePrice: 980,
    peRatio: 9.8,
    marketCap: '15.6 T',
    yahooSymbol: 'BFIN.JK',
    description: 'Perusahaan pembiayaan multiguna independen terbesar di Indonesia.',
  },
  {
    ticker: 'ADMF',
    name: 'Adira Dinamika Multi Finance Tbk',
    sector: 'Financials',
    basePrice: 10400,
    peRatio: 6.4,
    marketCap: '10.4 T',
    yahooSymbol: 'ADMF.JK',
    description: 'Perusahaan pembiayaan otomotif terkemuka anak usaha Bank Danamon.',
  },
  {
    ticker: 'TUGU',
    name: 'Asuransi Tugu Pratama Indonesia Tbk',
    sector: 'Financials',
    basePrice: 1180,
    peRatio: 4.8,
    marketCap: '4.2 T',
    yahooSymbol: 'TUGU.JK',
    description: 'Perusahaan asuransi umum anak usaha Pertamina dengan valuasi PBV rendah.',
  },

  // ==========================================
  // 2. CONSUMER NON-CYCLICALS (KONSUMSI PRIMER)
  // ==========================================
  {
    ticker: 'UNVR',
    name: 'Unilever Indonesia Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 2280,
    peRatio: 18.5,
    marketCap: '87 T',
    yahooSymbol: 'UNVR.JK',
    description: 'Produsen FMCG terkemuka dengan merek Lifebuoy, Pepsodent, Sunsilk, Bango.',
  },
  {
    ticker: 'ICBP',
    name: 'Indofood CBP Sukses Makmur Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 11800,
    peRatio: 15.2,
    marketCap: '137 T',
    yahooSymbol: 'ICBP.JK',
    description: 'Produsen mi instan Indomie terbesar di dunia dan produk makanan kemasan.',
  },
  {
    ticker: 'INDF',
    name: 'Indofood Sukses Makmur Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 6950,
    peRatio: 7.2,
    marketCap: '61 T',
    yahooSymbol: 'INDF.JK',
    description: 'Holding agribisnis dan produsen makanan terbesar di Indonesia (Bogasari, ICBP).',
  },
  {
    ticker: 'MYOR',
    name: 'Mayora Indah Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 2600,
    peRatio: 18.9,
    marketCap: '58 T',
    yahooSymbol: 'MYOR.JK',
    description: 'Produsen biskuit Roma, Kopiko, Torabika, Danisa yang diekspor ke 100+ negara.',
  },
  {
    ticker: 'KLBF',
    name: 'Kalbe Farma Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 1680,
    peRatio: 24.1,
    marketCap: '78 T',
    yahooSymbol: 'KLBF.JK',
    description: 'Perusahaan farmasi dan produk kesehatan konsumen terbesar di Asia Tenggara.',
  },
  {
    ticker: 'SIDO',
    name: 'Industri Jamu dan Farmasi Sido Muncul Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 660,
    peRatio: 18.4,
    marketCap: '19.8 T',
    yahooSymbol: 'SIDO.JK',
    description: 'Produsen jamu herbal Tolak Angin dan suplemen herbal dengan margin laba tinggi.',
  },
  {
    ticker: 'AMRT',
    name: 'Sumber Alfaria Trijaya Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 3120,
    peRatio: 36.2,
    marketCap: '129 T',
    yahooSymbol: 'AMRT.JK',
    description: 'Pengelola jaringan minimarket Alfamart terbesar di Indonesia dengan 19.000+ gerai.',
  },
  {
    ticker: 'MIDI',
    name: 'Midi Utama Indonesia Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 420,
    peRatio: 22.0,
    marketCap: '14.0 T',
    yahooSymbol: 'MIDI.JK',
    description: 'Pengelola jaringan minimarket Alfamidi dan Lawson anak usaha Alfamart.',
  },
  {
    ticker: 'CMRY',
    name: 'Cisarua Mountain Dairy Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 5100,
    peRatio: 28.5,
    marketCap: '40.4 T',
    yahooSymbol: 'CMRY.JK',
    description: 'Produsen yogurt, susu Cimory, dan sosis Kanzler dengan pertumbuhan pesat.',
  },
  {
    ticker: 'CPIN',
    name: 'Charoen Pokphand Indonesia Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 4950,
    peRatio: 24.2,
    marketCap: '81 T',
    yahooSymbol: 'CPIN.JK',
    description: 'Produsen pakan ternak, daging ayam olahan (Fiesta), dan peternakan unggas terbesar.',
  },
  {
    ticker: 'JPFA',
    name: 'Japfa Comfeed Indonesia Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 1620,
    peRatio: 11.2,
    marketCap: '19.0 T',
    yahooSymbol: 'JPFA.JK',
    description: 'Perusahaan agribisnis pakan ternak dan pengolahan protein hewani (So Good).',
  },
  {
    ticker: 'HMSP',
    name: 'H.M. Sampoerna Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 680,
    peRatio: 10.4,
    marketCap: '79 T',
    yahooSymbol: 'HMSP.JK',
    description: 'Produsen rokok kretek Dji Sam Soe & Sampoerna A Mild afiliasi Philip Morris.',
  },
  {
    ticker: 'GGRM',
    name: 'Gudang Garam Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 15400,
    peRatio: 6.8,
    marketCap: '29.6 T',
    yahooSymbol: 'GGRM.JK',
    description: 'Produsen rokok kretek legendaris Surya 16 dan Gudang Garam International.',
  },
  {
    ticker: 'CLEO',
    name: 'Sariguna Primatirta Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 1250,
    peRatio: 38.0,
    marketCap: '15.0 T',
    yahooSymbol: 'CLEO.JK',
    description: 'Produsen air minum dalam kemasan Cleo bagian dari Tanobel Group.',
  },
  {
    ticker: 'ROTI',
    name: 'Nippon Indosari Corpindo Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 1020,
    peRatio: 18.0,
    marketCap: '6.3 T',
    yahooSymbol: 'ROTI.JK',
    description: 'Produsen roti Sari Roti dengan pangsa pasar roti massal terbesar di Indonesia.',
  },
  {
    ticker: 'AALI',
    name: 'Astra Agro Lestari Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 6450,
    peRatio: 11.8,
    marketCap: '12.4 T',
    yahooSymbol: 'AALI.JK',
    description: 'Perusahaan perkebunan kelapa sawit dan CPO anak usaha Astra International.',
  },
  {
    ticker: 'LSIP',
    name: 'PP London Sumatra Indonesia Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 1010,
    peRatio: 9.4,
    marketCap: '6.9 T',
    yahooSymbol: 'LSIP.JK',
    description: 'Perkebunan kelapa sawit, karet, dan kakao anak usaha Salim Group.',
  },
  {
    ticker: 'TAPG',
    name: 'Triputra Agro Persada Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 880,
    peRatio: 8.5,
    marketCap: '17.4 T',
    yahooSymbol: 'TAPG.JK',
    description: 'Produsen CPO grup Triputra dengan umur tanaman prima dan produktivitas tinggi.',
  },

  // ==========================================
  // 3. CONSUMER CYCLICALS (KONSUMSI SEKUNDER)
  // ==========================================
  {
    ticker: 'ASII',
    name: 'Astra International Tbk',
    sector: 'Consumer Cyclicals',
    basePrice: 5125,
    peRatio: 6.8,
    marketCap: '207 T',
    yahooSymbol: 'ASII.JK',
    description: 'Konglomerasi otomotif (Toyota, Daihatsu, Honda), alat berat (UNTR), dan jasa keuangan.',
  },
  {
    ticker: 'AUTO',
    name: 'Astra Otoparts Tbk',
    sector: 'Consumer Cyclicals',
    basePrice: 2240,
    peRatio: 5.9,
    marketCap: '10.8 T',
    yahooSymbol: 'AUTO.JK',
    description: 'Produsen suku cadang otomotif terbesar di Indonesia anak usaha Grup Astra.',
  },
  {
    ticker: 'SMSM',
    name: 'Selamat Sempurna Tbk',
    sector: 'Consumer Cyclicals',
    basePrice: 1950,
    peRatio: 11.5,
    marketCap: '11.2 T',
    yahooSymbol: 'SMSM.JK',
    description: 'Produsen filter Sakura dan radiator otomotif dengan pasar ekspor 100+ negara.',
  },
  {
    ticker: 'GJTL',
    name: 'Gajah Tunggal Tbk',
    sector: 'Consumer Cyclicals',
    basePrice: 1220,
    peRatio: 4.5,
    marketCap: '4.2 T',
    yahooSymbol: 'GJTL.JK',
    description: 'Produsen ban GT Radial dan IRC terbesar di Asia Tenggara.',
  },
  {
    ticker: 'MAPI',
    name: 'Mitra Adiperkasa Tbk',
    sector: 'Consumer Cyclicals',
    basePrice: 1680,
    peRatio: 13.9,
    marketCap: '27 T',
    yahooSymbol: 'MAPI.JK',
    description: 'Peritel gaya hidup pengelola gerai Starbucks, Zara, Sephora, dan Foot Locker.',
  },
  {
    ticker: 'MAPA',
    name: 'MAP Aktif Adiperkasa Tbk',
    sector: 'Consumer Cyclicals',
    basePrice: 940,
    peRatio: 14.5,
    marketCap: '26.8 T',
    yahooSymbol: 'MAPA.JK',
    description: 'Peritel perlengkapan olahraga Sports Station, Planet Sports, dan Foot Locker.',
  },
  {
    ticker: 'ACES',
    name: 'Aspirasi Hidup Indonesia Tbk',
    sector: 'Consumer Cyclicals',
    basePrice: 840,
    peRatio: 17.2,
    marketCap: '14.4 T',
    yahooSymbol: 'ACES.JK',
    description: 'Peritel perlengkapan rumah tangga dan perkakas modern (ex-Ace Hardware).',
  },
  {
    ticker: 'ERAA',
    name: 'Erajaya Swasembada Tbk',
    sector: 'Consumer Cyclicals',
    basePrice: 430,
    peRatio: 8.1,
    marketCap: '6.8 T',
    yahooSymbol: 'ERAA.JK',
    description: 'Distributor dan peritel smartphone (iBox Apple, Erafone, Samsung Store).',
  },
  {
    ticker: 'RALS',
    name: 'Ramayana Lestari Sentosa Tbk',
    sector: 'Consumer Cyclicals',
    basePrice: 470,
    peRatio: 9.8,
    marketCap: '3.1 T',
    yahooSymbol: 'RALS.JK',
    description: 'Jaringan department store dan supermarket pakaian menengah-bawah.',
  },
  {
    ticker: 'SCMA',
    name: 'Surya Citra Media Tbk',
    sector: 'Consumer Cyclicals',
    basePrice: 145,
    peRatio: 16.0,
    marketCap: '10.7 T',
    yahooSymbol: 'SCMA.JK',
    description: 'Grup media pengelola stasiun TV SCTV, Indosiar, dan platform streaming Vidio.',
  },

  // ==========================================
  // 4. ENERGY (ENERGI, BATU BARA & MIGAS)
  // ==========================================
  {
    ticker: 'ADRO',
    name: 'Adaro Energy Indonesia Tbk',
    sector: 'Energy',
    basePrice: 3620,
    peRatio: 4.8,
    marketCap: '112 T',
    yahooSymbol: 'ADRO.JK',
    description: 'Produsen batu bara termal dan metalurgi terintegrasi dengan ekspansi energi hijau.',
  },
  {
    ticker: 'PTBA',
    name: 'Bukit Asam Tbk',
    sector: 'Energy',
    basePrice: 2820,
    peRatio: 6.1,
    marketCap: '32 T',
    yahooSymbol: 'PTBA.JK',
    description: 'BUMN tambang batu bara dengan cadangan melimpah di Sumatera Selatan.',
  },
  {
    ticker: 'ITMG',
    name: 'Indo Tambangraya Megah Tbk',
    sector: 'Energy',
    basePrice: 26800,
    peRatio: 4.9,
    marketCap: '30 T',
    yahooSymbol: 'ITMG.JK',
    description: 'Eksportir batu bara kalori tinggi dengan reputasi dividen yield jumbo.',
  },
  {
    ticker: 'PGAS',
    name: 'Perusahaan Gas Negara Tbk',
    sector: 'Energy',
    basePrice: 1540,
    peRatio: 7.2,
    marketCap: '37 T',
    yahooSymbol: 'PGAS.JK',
    description: 'Subholding gas Pertamina pengelola jaringan transmisi dan distribusi gas bumi.',
  },
  {
    ticker: 'MEDC',
    name: 'Medco Energi Internasional Tbk',
    sector: 'Energy',
    basePrice: 1280,
    peRatio: 5.4,
    marketCap: '32 T',
    yahooSymbol: 'MEDC.JK',
    description: 'Perusahaan eksplorasi dan produksi minyak, gas bumi, tembaga (AMMAN), dan panas bumi.',
  },
  {
    ticker: 'AKRA',
    name: 'AKR Corporindo Tbk',
    sector: 'Energy',
    basePrice: 1510,
    peRatio: 10.8,
    marketCap: '30 T',
    yahooSymbol: 'AKRA.JK',
    description: 'Distributor BBM industri, bahan kimia dasar, dan pengelola kawasan industri JIIPE.',
  },
  {
    ticker: 'BUMI',
    name: 'Bumi Resources Tbk',
    sector: 'Energy',
    basePrice: 135,
    peRatio: 12.5,
    marketCap: '50 T',
    yahooSymbol: 'BUMI.JK',
    description: 'Produsen batu bara terbesar di Indonesia (KPC dan Arutmin) kolaborasi Bakrie & Salim.',
  },
  {
    ticker: 'INDY',
    name: 'Indika Energy Tbk',
    sector: 'Energy',
    basePrice: 1520,
    peRatio: 6.2,
    marketCap: '7.9 T',
    yahooSymbol: 'INDY.JK',
    description: 'Perusahaan energi terdiversifikasi dengan anak usaha motor listrik ALVA.',
  },
  {
    ticker: 'HRUM',
    name: 'Harum Energy Tbk',
    sector: 'Energy',
    basePrice: 1260,
    peRatio: 8.9,
    marketCap: '17.0 T',
    yahooSymbol: 'HRUM.JK',
    description: 'Produsen batu bara yang bertransformasi agresif ke pengolahan nikel dan baterai EV.',
  },
  {
    ticker: 'DOID',
    name: 'Delta Dunia Makmur Tbk',
    sector: 'Energy',
    basePrice: 650,
    peRatio: 7.5,
    marketCap: '5.6 T',
    yahooSymbol: 'DOID.JK',
    description: 'Kontraktor jasa penambangan batu bara terbesar kedua di Indonesia (BUMA).',
  },
  {
    ticker: 'ELSA',
    name: 'Elnusa Tbk',
    sector: 'Energy',
    basePrice: 480,
    peRatio: 6.1,
    marketCap: '3.5 T',
    yahooSymbol: 'ELSA.JK',
    description: 'Perusahaan jasa hulu migas, logistik BBM, dan kelautan anak usaha Pertamina Hulu.',
  },

  // ==========================================
  // 5. BASIC MATERIALS (BARANG BAKU & LOGAM)
  // ==========================================
  {
    ticker: 'ANTM',
    name: 'Aneka Tambang Tbk',
    sector: 'Basic Materials',
    basePrice: 1580,
    peRatio: 14.1,
    marketCap: '38 T',
    yahooSymbol: 'ANTM.JK',
    description: 'BUMN tambang emas, feronikel, bauksit, dan bagian dari ekosistem baterai MIND ID.',
  },
  {
    ticker: 'INCO',
    name: 'Vale Indonesia Tbk',
    sector: 'Basic Materials',
    basePrice: 3820,
    peRatio: 13.8,
    marketCap: '38 T',
    yahooSymbol: 'INCO.JK',
    description: 'Produsen nikel dalam matte terkemuka di Sorowako, Sulawesi Selatan.',
  },
  {
    ticker: 'MDKA',
    name: 'Merdeka Copper Gold Tbk',
    sector: 'Basic Materials',
    basePrice: 2360,
    peRatio: 42.0,
    marketCap: '56 T',
    yahooSymbol: 'MDKA.JK',
    description: 'Perusahaan tambang emas Tujuh Bukit, tembaga Wetar, dan nikel HPAL Grup Saratoga.',
  },
  {
    ticker: 'AMMN',
    name: 'Amman Mineral Internasional Tbk',
    sector: 'Basic Materials',
    basePrice: 9450,
    peRatio: 38.5,
    marketCap: '685 T',
    yahooSymbol: 'AMMN.JK',
    description: 'Pengelola tambang tembaga dan emas raksasa Batu Hijau di Nusa Tenggara Barat.',
  },
  {
    ticker: 'TPIA',
    name: 'Chandra Asri Pacific Tbk',
    sector: 'Basic Materials',
    basePrice: 8700,
    peRatio: 65.0,
    marketCap: '752 T',
    yahooSymbol: 'TPIA.JK',
    description: 'Produsen petrokimia terintegrasi terbesar di Indonesia bagian dari Barito Pacific.',
  },
  {
    ticker: 'BRPT',
    name: 'Barito Pacific Tbk',
    sector: 'Basic Materials',
    basePrice: 1040,
    peRatio: 48.0,
    marketCap: '97 T',
    yahooSymbol: 'BRPT.JK',
    description: 'Holding company Prajogo Pangestu pengendali TPIA (petrokimia) dan BREN (panas bumi).',
  },
  {
    ticker: 'INKP',
    name: 'Indah Kiat Pulp & Paper Tbk',
    sector: 'Basic Materials',
    basePrice: 8150,
    peRatio: 6.2,
    marketCap: '44 T',
    yahooSymbol: 'INKP.JK',
    description: 'Produsen pulp dan kertas budaya terbesar Sinarmas Group dengan pasar global.',
  },
  {
    ticker: 'TKIM',
    name: 'Pabrik Kertas Tjiwi Kimia Tbk',
    sector: 'Basic Materials',
    basePrice: 7200,
    peRatio: 6.8,
    marketCap: '22 T',
    yahooSymbol: 'TKIM.JK',
    description: 'Produsen kertas tulis, cetak, dan kemasan industri Sinarmas Group.',
  },
  {
    ticker: 'SMGR',
    name: 'Semen Indonesia (Persero) Tbk',
    sector: 'Basic Materials',
    basePrice: 3850,
    peRatio: 12.5,
    marketCap: '26 T',
    yahooSymbol: 'SMGR.JK',
    description: 'BUMN holding semen terbesar di Asia Tenggara dengan merek Semen Gresik & Holcim.',
  },
  {
    ticker: 'INTP',
    name: 'Indocement Tunggal Prakarsa Tbk',
    sector: 'Basic Materials',
    basePrice: 6800,
    peRatio: 14.8,
    marketCap: '25 T',
    yahooSymbol: 'INTP.JK',
    description: 'Produsen Semen Tiga Roda dengan pabrik utama di Citereup dan Cirebon.',
  },
  {
    ticker: 'NCKL',
    name: 'Trimegah Bangun Persada Tbk',
    sector: 'Basic Materials',
    basePrice: 890,
    peRatio: 9.8,
    marketCap: '56.1 T',
    yahooSymbol: 'NCKL.JK',
    description: 'Pelopor pemurnian nikel HPAL untuk material baterai kendaraan listrik di Pulau Obi.',
  },
  {
    ticker: 'MBMA',
    name: 'Merdeka Battery Materials Tbk',
    sector: 'Basic Materials',
    basePrice: 530,
    peRatio: 28.0,
    marketCap: '57.2 T',
    yahooSymbol: 'MBMA.JK',
    description: 'Produsen bahan baku baterai nikel HPAL dan smelter RKEF anak usaha MDKA.',
  },
  {
    ticker: 'TINS',
    name: 'Timah Tbk',
    sector: 'Basic Materials',
    basePrice: 1120,
    peRatio: 12.0,
    marketCap: '8.3 T',
    yahooSymbol: 'TINS.JK',
    description: 'Produsen timah murni batangan terbesar kedua di dunia anggota holding MIND ID.',
  },

  // ==========================================
  // 6. HEALTHCARE (KESEHATAN & RUMAH SAKIT)
  // ==========================================
  {
    ticker: 'MIKA',
    name: 'Mitra Keluarga Karyasehat Tbk',
    sector: 'Healthcare',
    basePrice: 2850,
    peRatio: 32.0,
    marketCap: '40.6 T',
    yahooSymbol: 'MIKA.JK',
    description: 'Jaringan rumah sakit swasta premium Mitra Keluarga dengan margin profitabilitas tinggi.',
  },
  {
    ticker: 'HEAL',
    name: 'Medikaloka Hermina Tbk',
    sector: 'Healthcare',
    basePrice: 1420,
    peRatio: 34.5,
    marketCap: '21.5 T',
    yahooSymbol: 'HEAL.JK',
    description: 'Jaringan RS Hermina spesialis ibu & anak dengan 45+ cabang di seluruh Indonesia.',
  },
  {
    ticker: 'SILO',
    name: 'Siloam International Hospitals Tbk',
    sector: 'Healthcare',
    basePrice: 2900,
    peRatio: 26.0,
    marketCap: '37.7 T',
    yahooSymbol: 'SILO.JK',
    description: 'Jaringan RS Siloam terbesar di Indonesia bagian dari Lippo Group.',
  },
  {
    ticker: 'PRDA',
    name: 'Prodia Widyahusada Tbk',
    sector: 'Healthcare',
    basePrice: 3200,
    peRatio: 14.5,
    marketCap: '3.0 T',
    yahooSymbol: 'PRDA.JK',
    description: 'Laboratorium klinik rujukan terbesar di Indonesia dengan akreditasi internasional.',
  },
  {
    ticker: 'TSPC',
    name: 'Tempo Scan Pacific Tbk',
    sector: 'Healthcare',
    basePrice: 2450,
    peRatio: 9.8,
    marketCap: '11.0 T',
    yahooSymbol: 'TSPC.JK',
    description: 'Produsen obat Bodrex, Hemaviton, dan produk farmasi OTC terkemuka.',
  },

  // ==========================================
  // 7. TECHNOLOGY (TEKNOLOGI & DIGITAL)
  // ==========================================
  {
    ticker: 'GOTO',
    name: 'GoTo Gojek Tokopedia Tbk',
    sector: 'Technology',
    basePrice: 62,
    peRatio: -12.0,
    marketCap: '74 T',
    yahooSymbol: 'GOTO.JK',
    description: 'Ekosistem on-demand (Gojek) dan financial technology (GoPay) terbesar di Indonesia.',
  },
  {
    ticker: 'BUKA',
    name: 'Bukalapak.com Tbk',
    sector: 'Technology',
    basePrice: 128,
    peRatio: -18.0,
    marketCap: '13 T',
    yahooSymbol: 'BUKA.JK',
    description: 'Platform e-commerce dan jaringan warung O2O digital terbesar di Indonesia.',
  },
  {
    ticker: 'EMTK',
    name: 'Elang Mahkota Teknologi Tbk',
    sector: 'Technology',
    basePrice: 420,
    peRatio: 22.0,
    marketCap: '25.7 T',
    yahooSymbol: 'EMTK.JK',
    description: 'Konglomerasi teknologi, media digital (SCMA), dan rumah sakit (EMC Healthcare).',
  },
  {
    ticker: 'WIRG',
    name: 'WIR ASIA Tbk',
    sector: 'Technology',
    basePrice: 105,
    peRatio: 19.5,
    marketCap: '1.2 T',
    yahooSymbol: 'WIRG.JK',
    description: 'Pengembang teknologi augmented reality (AR), virtual reality (VR), dan AI berbasis interaktif.',
  },
  {
    ticker: 'BELI',
    name: 'Global Digital Niaga Tbk (Blibli)',
    sector: 'Technology',
    basePrice: 440,
    peRatio: -15.0,
    marketCap: '52.1 T',
    yahooSymbol: 'BELI.JK',
    description: 'Ekosistem omnichannel e-commerce Blibli, Tiket.com, dan Ranch Market Grup Djarum.',
  },
  {
    ticker: 'MTDL',
    name: 'Metrodata Electronics Tbk',
    sector: 'Technology',
    basePrice: 640,
    peRatio: 12.0,
    marketCap: '7.8 T',
    yahooSymbol: 'MTDL.JK',
    description: 'Distributor solusi IT, perangkat keras, cloud, dan integrasi sistem enterprise.',
  },

  // ==========================================
  // 8. INFRASTRUCTURE & UTILITIES (INFRASTRUKTUR & TELKO)
  // ==========================================
  {
    ticker: 'TLKM',
    name: 'Telkom Indonesia (Persero) Tbk',
    sector: 'Infrastructure',
    basePrice: 3020,
    peRatio: 12.4,
    marketCap: '299 T',
    yahooSymbol: 'TLKM.JK',
    description: 'BUMN telekomunikasi terbesar dengan layanan Telkomsel, IndiHome, dan data center.',
  },
  {
    ticker: 'ISAT',
    name: 'Indosat Ooredoo Hutchison Tbk',
    sector: 'Infrastructure',
    basePrice: 2320,
    peRatio: 14.8,
    marketCap: '75 T',
    yahooSymbol: 'ISAT.JK',
    description: 'Operator seluler IM3 & Tri dengan basis pelanggan broadband data terbesar kedua.',
  },
  {
    ticker: 'EXCL',
    name: 'XL Axiata Tbk',
    sector: 'Infrastructure',
    basePrice: 2240,
    peRatio: 16.5,
    marketCap: '29.4 T',
    yahooSymbol: 'EXCL.JK',
    description: 'Operator seluler dan fixed broadband XL SATU bagian dari Axiata Group Berhad.',
  },
  {
    ticker: 'TOWR',
    name: 'Sarana Menara Nusantara Tbk',
    sector: 'Infrastructure',
    basePrice: 830,
    peRatio: 12.8,
    marketCap: '42.3 T',
    yahooSymbol: 'TOWR.JK',
    description: 'Penyedia menara telekomunikasi dan jaringan fiber optik Protelindo Grup Djarum.',
  },
  {
    ticker: 'TBIG',
    name: 'Tower Bersama Infrastructure Tbk',
    sector: 'Infrastructure',
    basePrice: 1780,
    peRatio: 26.5,
    marketCap: '40.3 T',
    yahooSymbol: 'TBIG.JK',
    description: 'Penyedia infrastruktur menara BTS telekomunikasi independen Grup Saratoga.',
  },
  {
    ticker: 'JSMR',
    name: 'Jasa Marga (Persero) Tbk',
    sector: 'Infrastructure',
    basePrice: 4750,
    peRatio: 9.8,
    marketCap: '34.5 T',
    yahooSymbol: 'JSMR.JK',
    description: 'BUMN pengembang dan operator jalan tol terbesar di Indonesia (Trans Jawa, Jabotabek).',
  },
  {
    ticker: 'PGEO',
    name: 'Pertamina Geothermal Energy Tbk',
    sector: 'Infrastructure',
    basePrice: 1140,
    peRatio: 18.0,
    marketCap: '47.2 T',
    yahooSymbol: 'PGEO.JK',
    description: 'Pelopor pembangkit listrik tenaga panas bumi (geothermal) anak usaha Pertamina.',
  },
  {
    ticker: 'BREN',
    name: 'Barito Renewables Energy Tbk',
    sector: 'Infrastructure',
    basePrice: 8900,
    peRatio: 95.0,
    marketCap: '1.190 T',
    yahooSymbol: 'BREN.JK',
    description: 'Produsen energi baru terbarukan (panas bumi Star Energy) Grup Prajogo Pangestu.',
  },
  {
    ticker: 'PTPP',
    name: 'PP (Persero) Tbk',
    sector: 'Infrastructure',
    basePrice: 380,
    peRatio: 8.5,
    marketCap: '2.3 T',
    yahooSymbol: 'PTPP.JK',
    description: 'BUMN konstruksi, investasi infrastruktur, gedung, dan pembangunan IKN Nusantara.',
  },
  {
    ticker: 'ADHI',
    name: 'Adhi Karya (Persero) Tbk',
    sector: 'Infrastructure',
    basePrice: 260,
    peRatio: 9.2,
    marketCap: '2.2 T',
    yahooSymbol: 'ADHI.JK',
    description: 'BUMN konstruksi spesialis transportasi massal LRT Jabodebek dan jalan tol.',
  },
  {
    ticker: 'WIKA',
    name: 'Wijaya Karya (Persero) Tbk',
    sector: 'Infrastructure',
    basePrice: 290,
    peRatio: -8.0,
    marketCap: '2.6 T',
    yahooSymbol: 'WIKA.JK',
    description: 'BUMN konstruksi sipil, jembatan, bandara, dan fasilitas industri strategis.',
  },

  // ==========================================
  // 9. TRANSPORTATION & LOGISTICS (TRANSPORTASI)
  // ==========================================
  {
    ticker: 'BIRD',
    name: 'Blue Bird Tbk',
    sector: 'Transportation',
    basePrice: 2020,
    peRatio: 10.4,
    marketCap: '5.0 T',
    yahooSymbol: 'BIRD.JK',
    description: 'Operator taksi dan transportasi darat Bluebird dengan armada listrik modern.',
  },
  {
    ticker: 'ASSA',
    name: 'Adi Sarana Armada Tbk',
    sector: 'Transportation',
    basePrice: 780,
    peRatio: 13.5,
    marketCap: '2.9 T',
    yahooSymbol: 'ASSA.JK',
    description: 'Perusahaan logistik AnterAja, lelang mobil JBA, dan rental kendaraan korporasi Triputra.',
  },
  {
    ticker: 'SMDR',
    name: 'Samudera Indonesia Tbk',
    sector: 'Transportation',
    basePrice: 320,
    peRatio: 6.2,
    marketCap: '5.2 T',
    yahooSymbol: 'SMDR.JK',
    description: 'Perusahaan pelayaran kargo peti kemas, logistik laut, dan jasa pelabuhan terintegrasi.',
  },
  {
    ticker: 'TMAS',
    name: 'Temas Tbk',
    sector: 'Transportation',
    basePrice: 155,
    peRatio: 8.9,
    marketCap: '8.8 T',
    yahooSymbol: 'TMAS.JK',
    description: 'Pelayaran peti kemas domestik pelopor tol laut nusantara.',
  },
  {
    ticker: 'GIAA',
    name: 'Garuda Indonesia (Persero) Tbk',
    sector: 'Transportation',
    basePrice: 58,
    peRatio: -5.0,
    marketCap: '5.3 T',
    yahooSymbol: 'GIAA.JK',
    description: 'Maskapai penerbangan nasional pembawa bendera Republik Indonesia.',
  },

  // ==========================================
  // 10. PROPERTIES & REAL ESTATE (PROPERTI)
  // ==========================================
  {
    ticker: 'CTRA',
    name: 'Ciputra Development Tbk',
    sector: 'Real Estate',
    basePrice: 1240,
    peRatio: 10.8,
    marketCap: '23 T',
    yahooSymbol: 'CTRA.JK',
    description: 'Pengembang kota mandiri CitraGarden dan proyek properti di 30+ kota di Indonesia.',
  },
  {
    ticker: 'BSDE',
    name: 'Bumi Serpong Damai Tbk',
    sector: 'Real Estate',
    basePrice: 1180,
    peRatio: 8.4,
    marketCap: '25 T',
    yahooSymbol: 'BSDE.JK',
    description: 'Pengembang kota mandiri BSD City dan proyek komersial Sinarmas Land.',
  },
  {
    ticker: 'PWON',
    name: 'Pakuwon Jati Tbk',
    sector: 'Real Estate',
    basePrice: 440,
    peRatio: 9.1,
    marketCap: '21 T',
    yahooSymbol: 'PWON.JK',
    description: 'Raja mal komersial (Kota Kasablanka, Gandaria City, Tunjungan Plaza) dengan recurring income kuat.',
  },
  {
    ticker: 'SMRA',
    name: 'Summarecon Agung Tbk',
    sector: 'Real Estate',
    basePrice: 610,
    peRatio: 11.2,
    marketCap: '10.1 T',
    yahooSymbol: 'SMRA.JK',
    description: 'Pengembang township Summarecon Kelapa Gading, Serpong, Bekasi, dan Bandung.',
  },
  {
    ticker: 'PANI',
    name: 'Pantai Indah Kapuk Dua Tbk',
    sector: 'Real Estate',
    basePrice: 14800,
    peRatio: 85.0,
    marketCap: '246 T',
    yahooSymbol: 'PANI.JK',
    description: 'Pengembang megaproyek kawasan terpadu Pantai Indah Kapuk 2 (Agung Sedayu & Salim Group).',
  },
  {
    ticker: 'ASRI',
    name: 'Alam Sutera Realty Tbk',
    sector: 'Real Estate',
    basePrice: 210,
    peRatio: 7.2,
    marketCap: '4.1 T',
    yahooSymbol: 'ASRI.JK',
    description: 'Pengembang kota mandiri Alam Sutera dan Suvarna Sutera di Tangerang.',
  },
  {
    ticker: 'KIJA',
    name: 'Kawasan Industri Jababeka Tbk',
    sector: 'Real Estate',
    basePrice: 165,
    peRatio: 9.0,
    marketCap: '3.4 T',
    yahooSymbol: 'KIJA.JK',
    description: 'Pengembang kawasan industri kota Jababeka Cikarang dan pariwisata Tanjung Lesung.',
  },
  {
    ticker: 'SSIA',
    name: 'Surya Semesta Internusa Tbk',
    sector: 'Real Estate',
    basePrice: 1150,
    peRatio: 16.0,
    marketCap: '5.4 T',
    yahooSymbol: 'SSIA.JK',
    description: 'Pengembang Subang Smartpolitan, kawasan industri Suryacipta Karawang, dan hotel Gran Melia.',
  },
  {
    ticker: 'DMAS',
    name: 'Puradelta Lestari Tbk',
    sector: 'Real Estate',
    basePrice: 160,
    peRatio: 6.8,
    marketCap: '7.7 T',
    yahooSymbol: 'DMAS.JK',
    description: 'Pengembang Kota Deltamas Cikarang pusat klaster data center dengan dividen yield tinggi.',
  },

  // ==========================================
  // 11. INDUSTRIALS (INDUSTRI & MULTISEKTOR)
  // ==========================================
  {
    ticker: 'UNTR',
    name: 'United Tractors Tbk',
    sector: 'Industrials',
    basePrice: 26900,
    peRatio: 4.8,
    marketCap: '100 T',
    yahooSymbol: 'UNTR.JK',
    description: 'Distributor alat berat Komatsu, kontraktor tambang PAMA, dan tambang emas Martabe.',
  },
  {
    ticker: 'HEXA',
    name: 'Hexindo Adiperkasa Tbk',
    sector: 'Industrials',
    basePrice: 6200,
    peRatio: 5.9,
    marketCap: '5.2 T',
    yahooSymbol: 'HEXA.JK',
    description: 'Distributor tunggal alat berat ekskavator Hitachi di Indonesia dengan dividen konsisten.',
  },
  {
    ticker: 'KBLI',
    name: 'KMI Wire and Cable Tbk',
    sector: 'Industrials',
    basePrice: 340,
    peRatio: 7.2,
    marketCap: '1.4 T',
    yahooSymbol: 'KBLI.JK',
    description: 'Produsen kabel tembaga dan aluminium untuk transmisi kelistrikan PLN dan infrastruktur.',
  },
  {
    ticker: 'MARK',
    name: 'Mark Dynamics Indonesia Tbk',
    sector: 'Industrials',
    basePrice: 880,
    peRatio: 14.5,
    marketCap: '3.3 T',
    yahooSymbol: 'MARK.JK',
    description: 'Produsen cetakan sarung tangan karet keramik terbesar di dunia dengan pangsa pasar global 40%.',
  },
  {
    ticker: 'IMPC',
    name: 'Impack Pratama Industri Tbk',
    sector: 'Industrials',
    basePrice: 380,
    peRatio: 18.2,
    marketCap: '18.9 T',
    yahooSymbol: 'IMPC.JK',
    description: 'Produsen bahan bangunan atap polikarbonat Alderon, SolarTuff, dan bahan bangunan ramah lingkungan.',
  },
];
