export const DEFAULT_INITIAL_BALANCE = 100_000_000.0; // Rp 100.000.000
export const BUY_BROKER_FEE_RATE = 0.0015; // 0.15%
export const SELL_BROKER_FEE_RATE = 0.0025; // 0.25%
export const SHARES_PER_LOT = 100;

export interface StockInfo {
  ticker: string;
  name: string;
  sector: string;
  basePrice: number;
  peRatio: number;
  marketCap: string;
  yahooSymbol: string;
  description: string;
}

export const STOCKS: StockInfo[] = [
  // --- FINANCIALS ---
  {
    ticker: 'BBCA',
    name: 'Bank Central Asia Tbk',
    sector: 'Financials',
    basePrice: 10250,
    peRatio: 22.4,
    marketCap: '1.260 T',
    yahooSymbol: 'BBCA.JK',
    description: 'Bank swasta terbesar di Indonesia dengan kapitalisasi pasar terbesar di BEI.',
  },
  {
    ticker: 'BBRI',
    name: 'Bank Rakyat Indonesia (Persero) Tbk',
    sector: 'Financials',
    basePrice: 4890,
    peRatio: 12.8,
    marketCap: '741 T',
    yahooSymbol: 'BBRI.JK',
    description: 'Bank BUMN dengan fokus utama pembiayaan segmen UMKM dan mikro di Indonesia.',
  },
  {
    ticker: 'BMRI',
    name: 'Bank Mandiri (Persero) Tbk',
    sector: 'Financials',
    basePrice: 6550,
    peRatio: 10.9,
    marketCap: '611 T',
    yahooSymbol: 'BMRI.JK',
    description: 'Salah satu bank BUMN terbesar di Indonesia dengan aset korporasi terkuat.',
  },
  {
    ticker: 'BBNI',
    name: 'Bank Negara Indonesia (Persero) Tbk',
    sector: 'Financials',
    basePrice: 5300,
    peRatio: 9.4,
    marketCap: '197 T',
    yahooSymbol: 'BBNI.JK',
    description: 'Bank BUMN pelopor layanan perbankan internasional dan consumer banking.',
  },
  {
    ticker: 'BRIS',
    name: 'Bank Syariah Indonesia Tbk',
    sector: 'Financials',
    basePrice: 2850,
    peRatio: 18.2,
    marketCap: '131 T',
    yahooSymbol: 'BRIS.JK',
    description: 'Bank syariah terbesar di Indonesia hasil merger bank syariah BUMN.',
  },

  // --- TELECOMMUNICATION & TECH ---
  {
    ticker: 'TLKM',
    name: 'Telkom Indonesia (Persero) Tbk',
    sector: 'Telecommunication',
    basePrice: 3050,
    peRatio: 13.2,
    marketCap: '302 T',
    yahooSymbol: 'TLKM.JK',
    description: 'Perusahaan telekomunikasi digital terbesar di Indonesia (IndiHome & Telkomsel).',
  },
  {
    ticker: 'ISAT',
    name: 'Indosat Ooredoo Hutchison Tbk',
    sector: 'Telecommunication',
    basePrice: 2350,
    peRatio: 16.5,
    marketCap: '75 T',
    yahooSymbol: 'ISAT.JK',
    description: 'Operator telekomunikasi seluler digital terkemuka di Indonesia.',
  },
  {
    ticker: 'GOTO',
    name: 'GoTo Gojek Tokopedia Tbk',
    sector: 'Technology',
    basePrice: 58,
    peRatio: -4.2,
    marketCap: '69 T',
    yahooSymbol: 'GOTO.JK',
    description: 'Ekosistem digital terintegrasi on-demand services, e-commerce, dan fintech.',
  },
  {
    ticker: 'BUKA',
    name: 'Bukalapak.com Tbk',
    sector: 'Technology',
    basePrice: 124,
    peRatio: -6.8,
    marketCap: '12 T',
    yahooSymbol: 'BUKA.JK',
    description: 'Platform e-commerce dan pemberdayaan warung UMKM digital di Indonesia.',
  },

  // --- CONSUMER & HEALTHCARE ---
  {
    ticker: 'ASII',
    name: 'Astra International Tbk',
    sector: 'Consumer Cyclicals',
    basePrice: 5075,
    peRatio: 7.2,
    marketCap: '205 T',
    yahooSymbol: 'ASII.JK',
    description: 'Konglomerat multinasional Indonesia di bidang otomotif, alat berat, dan agribisnis.',
  },
  {
    ticker: 'ICBP',
    name: 'Indofood CBP Sukses Makmur Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 11400,
    peRatio: 15.6,
    marketCap: '133 T',
    yahooSymbol: 'ICBP.JK',
    description: 'Produsen makanan olahan terkemuka di dunia, produsen mi instan legendaris Indomie.',
  },
  {
    ticker: 'INDF',
    name: 'Indofood Sukses Makmur Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 7150,
    peRatio: 7.8,
    marketCap: '62 T',
    yahooSymbol: 'INDF.JK',
    description: 'Perusahaan Total Food Solutions terintegrasi dari hulu hingga ke hilir.',
  },
  {
    ticker: 'UNVR',
    name: 'Unilever Indonesia Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 2280,
    peRatio: 18.5,
    marketCap: '87 T',
    yahooSymbol: 'UNVR.JK',
    description: 'Produsen barang konsumen cepat habis (FMCG) terkemuka dengan merek terpercaya.',
  },
  {
    ticker: 'MYOR',
    name: 'Mayora Indah Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 2580,
    peRatio: 17.1,
    marketCap: '57 T',
    yahooSymbol: 'MYOR.JK',
    description: 'Produsen makanan dan biskuit terkemuka dengan pasar ekspor ke lebih dari 100 negara.',
  },
  {
    ticker: 'KLBF',
    name: 'Kalbe Farma Tbk',
    sector: 'Healthcare',
    basePrice: 1520,
    peRatio: 23.4,
    marketCap: '71 T',
    yahooSymbol: 'KLBF.JK',
    description: 'Perusahaan farmasi dan produk kesehatan konsumen terbesar di Asia Tenggara.',
  },

  // --- ENERGY & MINING ---
  {
    ticker: 'AMMN',
    name: 'Amman Mineral Internasional Tbk',
    sector: 'Basic Materials',
    basePrice: 9450,
    peRatio: 35.1,
    marketCap: '685 T',
    yahooSymbol: 'AMMN.JK',
    description: 'Perusahaan tambang tembaga dan emas terbesar kedua di Indonesia di Batu Hijau.',
  },
  {
    ticker: 'ADRO',
    name: 'Adaro Energy Indonesia Tbk',
    sector: 'Energy',
    basePrice: 3680,
    peRatio: 4.8,
    marketCap: '117 T',
    yahooSymbol: 'ADRO.JK',
    description: 'Produsen batu bara terintegrasi dan energi hijau terkemuka di Indonesia.',
  },
  {
    ticker: 'PTBA',
    name: 'Bukit Asam Tbk',
    sector: 'Energy',
    basePrice: 2820,
    peRatio: 6.9,
    marketCap: '32 T',
    yahooSymbol: 'PTBA.JK',
    description: 'BUMN tambang batu bara dengan komitmen dividen jumbo tinggi bagi pemegang saham.',
  },
  {
    ticker: 'MEDC',
    name: 'Medco Energi Internasional Tbk',
    sector: 'Energy',
    basePrice: 1270,
    peRatio: 5.8,
    marketCap: '31 T',
    yahooSymbol: 'MEDC.JK',
    description: 'Perusahaan energi dan eksplorasi migas independen terkemuka di Asia Tenggara.',
  },
  {
    ticker: 'ANTM',
    name: 'Aneka Tambang Tbk',
    sector: 'Basic Materials',
    basePrice: 1590,
    peRatio: 13.8,
    marketCap: '38 T',
    yahooSymbol: 'ANTM.JK',
    description: 'BUMN pertambangan emas, nikel, dan bauksit terintegrasi anggota MIND ID.',
  },
  {
    ticker: 'INCO',
    name: 'Vale Indonesia Tbk',
    sector: 'Basic Materials',
    basePrice: 3880,
    peRatio: 14.5,
    marketCap: '38 T',
    yahooSymbol: 'INCO.JK',
    description: 'Produsen nikel matte terkemuka dengan biaya produksi terendah di dunia.',
  },
  {
    ticker: 'PGAS',
    name: 'Perusahaan Gas Negara Tbk',
    sector: 'Energy',
    basePrice: 1540,
    peRatio: 7.1,
    marketCap: '37 T',
    yahooSymbol: 'PGAS.JK',
    description: 'Subholding gas Pertamina pengelola jaringan transmisi dan distribusi gas nasional.',
  },

  // --- INFRASTRUCTURE & PROPERTIES ---
  {
    ticker: 'JSMR',
    name: 'Jasa Marga (Persero) Tbk',
    sector: 'Infrastructure',
    basePrice: 4780,
    peRatio: 8.9,
    marketCap: '34 T',
    yahooSymbol: 'JSMR.JK',
    description: 'Pengembang dan operator jalan tol terbesar di Indonesia.',
  },
  {
    ticker: 'SMGR',
    name: 'Semen Indonesia (Persero) Tbk',
    sector: 'Basic Materials',
    basePrice: 3720,
    peRatio: 11.2,
    marketCap: '25 T',
    yahooSymbol: 'SMGR.JK',
    description: 'Produsen semen terbesar di Asia Tenggara (Semen Padang, Semen Gresik, Semen Tonasa).',
  },
  {
    ticker: 'CTRA',
    name: 'Ciputra Development Tbk',
    sector: 'Real Estate',
    basePrice: 1240,
    peRatio: 10.8,
    marketCap: '23 T',
    yahooSymbol: 'CTRA.JK',
    description: 'Pengembang properti terkemuka dengan proyek kota mandiri di berbagai kota di Indonesia.',
  },
  {
    ticker: 'BSDE',
    name: 'Bumi Serpong Damai Tbk',
    sector: 'Real Estate',
    basePrice: 1180,
    peRatio: 8.4,
    marketCap: '25 T',
    yahooSymbol: 'BSDE.JK',
    description: 'Pengembang kota mandiri BSD City dan proyek properti komersial Sinarmas Land.',
  },
  {
    ticker: 'PWON',
    name: 'Pakuwon Jati Tbk',
    sector: 'Real Estate',
    basePrice: 440,
    peRatio: 9.1,
    marketCap: '21 T',
    yahooSymbol: 'PWON.JK',
    description: 'Raja mal dan pusat perbelanjaan di Jakarta dan Surabaya dengan recurring income solid.',
  },
  {
    ticker: 'MAPI',
    name: 'Mitra Adiperkasa Tbk',
    sector: 'Consumer Cyclicals',
    basePrice: 1680,
    peRatio: 13.9,
    marketCap: '27 T',
    yahooSymbol: 'MAPI.JK',
    description: 'Peritel gaya hidup terkemuka pengelola gerai Starbucks, Zara, Sephora, dan Foot Locker.',
  },
  {
    ticker: 'CPIN',
    name: 'Charoen Pokphand Indonesia Tbk',
    sector: 'Consumer Non-Cyclicals',
    basePrice: 4950,
    peRatio: 24.2,
    marketCap: '81 T',
    yahooSymbol: 'CPIN.JK',
    description: 'Produsen pakan ternak, daging ayam olahan (Fiesta), dan peternakan unggas terbesar di Indonesia.',
  },
];
